DEF_STATUS( OK,                             0,  "OK")

DEF_STATUS( CURR_LINE_IS_A_LABEL,           1,  "CURR_LINE_IS_A_LABEL")

DEF_STATUS( ERROR_GET_IN_OUT_FILES_NAMES,   2,  "ERROR_GET_IN_OUT_FILES_NAMES")

DEF_STATUS( ERROR_READ_INPUT_FILE,          3,  "ERROR_READ_INPUT_FILE")

DEF_STATUS( ERROR_CANT_OPEN_OUTPUT_FILE,    4,  "ERROR_CANT_OPEN_OUTPUT_FILE")

DEF_STATUS( ERROR_MEM_ALLOC,                5,  "ERROR_MEM_ALLOC")

DEF_STATUS( ERROR_UNKOWN_COMMAND,           6,  "ERROR_UNKOWN_COMMAND")

DEF_STATUS( ERROR_CMD_ARG,                  7,  "ERROR_CMD_ARG")

DEF_STATUS( ERROR_CMD_ARG_TOO_BIG,          8,  "ERROR_CMD_ARG_TOO_BIG")

DEF_STATUS( ERROR_LABEL_REDEFINED,          9,  "ERROR_LABEL_REDEFINED")

DEF_STATUS( ERROR_UNDEFINED_LABEL,          10, "ERROR_UNDEFINED_LABEL")
