DEF_STATUS( OK,                                 0,  "OK" )

DEF_STATUS( HLT,                                1,  "HLT" )

DEF_STATUS( ERROR_GET_IN_OUT_FILES_NAMES,       2,  "ERROR_GET_IN_OUT_FILES_NAMES" )

DEF_STATUS( ERROR_READ_INPUT_FILE,              3,  "ERROR_READ_INPUT_FILE" )

DEF_STATUS( ERROR_IN_PROG,                      4,  "ERROR_IN_PROG" )

DEF_STATUS( ERROR_NULL_SPU_PTR,                 5,  "ERROR_NULL_SPU_PTR" )

DEF_STATUS( ERROR_CONFIG_HAS_ERROR,             6,  "ERROR_CONFIG_HAS_ERROR" )

DEF_STATUS( ERROR_MEM_ALLOC_ERROR,              7,  "ERROR_MEM_ALLOC_ERROR" )

DEF_STATUS( ERROR_INP_FILE_HEADER_CORRUPTED,    8,  "ERROR_INP_FILE_HEADER_CORRUPTED" )

DEF_STATUS( ERROR_ZERO_BYTES_OF_CODE,           9,  "ERROR_ZERO_BYTES_OF_CODE" )

DEF_STATUS( ERROR_HEADER_WRONG_SIGN,            10, "ERROR_HEADER_WRONG_SIGN" )

DEF_STATUS( ERROR_INPUT_FILE_WRONG_VERSION,     11, "ERROR_INPUT_FILE_WRONG_VERSION" )

DEF_STATUS( ERROR_INPUT_FILE_CODE_CORRUPTED,    12, "ERROR_INPUT_FILE_CODE_CORRUPTED" )

DEF_STATUS( ERROR_STACK,                        13, "ERROR_STACK" )

DEF_STATUS( ERROR_UNKNOWN_CMD,                   14, "ERROR_UNKNOWN_CMD" )

DEF_STATUS( ERROR_WRONG_IN,                     15, "ERROR_WRONG_IN" )

DEF_STATUS( ERROR_DIV_BY_ZERO,                  16, "ERROR_DIV_BY_ZERO" )
