
DEF_STATUS( OK,                                 0, "OK" )

DEF_STATUS( ERROR_GET_IN_OUT_FILES_NAMES,       1, "ERROR_GET_IN_OUT_FILES_NAMES" )

DEF_STATUS( ERROR_READ_INPUT_FILE,              2, "ERROR_READ_INPUT_FILE" )

DEF_STATUS( ERROR_OPEN_OUTPUT_FILE,             3, "ERROR_OPEN_OUTPUT_FILE" )

DEF_STATUS( ERROR_MEM_ALLOC_ERROR,              4, "ERROR_MEM_ALLOC_ERROR" )

DEF_STATUS( ERROR_INP_FILE_HEADER_CORRUPTED,    5, "ERROR_INP_FILE_HEADER_CORRUPTED" )

DEF_STATUS( ERROR_INP_FILE_CORRUPTED,           6, "ERROR_INP_FILE_CORRUPTED" )

DEF_STATUS( ERROR_UNKNOWN_CMD,                   7, "ERROR_UNKNOWN_CMD" )
